<?php

namespace StockBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
  public function findProduit($id)
{
    $Query = $this->getEntityManager()->createQuery(
        "select A from StockBundle:Produit  A where A.categorie= :id")->setParameter('id',$id);
    return $Query->getResult();
}

    public function findName($nom)
    {
        $Query = $this->getEntityManager()->createQuery(
            "select A from StockBundle:Produit  A where A.nom LIKE :nom")->setParameter('nom','%'.$nom.'%');
        return $Query->getResult();
    }
}
