<?php

namespace AchatBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findByUser_Id($user){
        /*  $query= $this->getEntityManager()->createQueryBuilder()
          ->select('p')->from('ecommerceBundle:Panier','p')->where('p.user_id= :user')->setParameter('user',"%{$user}%");

              return $query->getResult();
  */

        $query = $this->getEntityManager()->createQuery("SELECT p FROM  AchatBundle\Entity\Panier AS p WHERE p.user_id=:user and p.etat=1")->setParameter('user',$user->getId());


        try {
            return $query->getOneOrNullResult();
        } catch (NoResultException $e) {
                dump($e);
        } catch (NonUniqueResultException $e) {
            dump($e);
        }
//        finally {
//            return 0;
//        }


    }



}
